### ISSUE TITLE
Windows: Does not install cli script in Scripts

### ISSUE THREAD

**Issue by raghur** [kennethreitz/xerox#22]
`pip install xerox` reports success but I don't find a cli executable script installed in Scripts

**Comment by iLoveTux** [comment]
I'm just putting this here for the next guy.

Looking into this, I found a couple of things which are curious and one reason that the cli executable is unavailable after a `pip install xerox`.

1. The package on PyPI is not the same as what is here on GitHub (although the respective setup.py files declare that they are the same version).
2. The package on PyPI does not declare the `console_scripts` `entry_point`
3. The package on PyPI does not have a `main` function declared in the `__init__.py` file, so even if the `console_scripts` `entry_point` was defined there would be no way to run it.

I have found that you can get the cli executable in  two ways:

1. Have `pip` grab the package from GitHub ie. `pip install git+https://github.com/kennethreitz/xerox`
2. Download the zip file of this repository (link is on the bottom right of the main page), extract, cd into directory and issue the following command `python setup.py install`

Also, and this is unrelated to this issue, but I found that I needed to install the xclip package (running Fedora 22) `sudo dnf install xclip`

After doing these things I was able to get it working. I have found the cli executable to be extremely useful. For one thing, when `bash`ing on the terminal I am no longer using temporary files when things get complex, I just store it in my clipboard.

**Comment by kennethreitz** [comment]
New version released! https://pypi.python.org/pypi/xerox
