### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by catch22** [kennethreitz/xerox#26]
The version advertised in `setup.py` does not match the version specified in `core.py`.

**Comment by kennethreitz** [comment]
New version released! https://pypi.python.org/pypi/xerox

**Comment by catch22** [comment]
Just to clarify: I was referring to https://github.com/kennethreitz/xerox/blob/master/xerox/core.py#L4

**Comment by kennethreitz** [comment]
@catch22 Ah, thanks! Fixed now :)

**Comment by catch22** [comment]
Thanks :-)
